[package]
name = "viletech-client"
version = "0.0.0"
edition = "2021"

authors = ["***REMOVED***"]
categories = ["games", "game-engines", "game-development"]
description = "Client for the VileTech Engine"
homepage = "https://github.com/***REMOVED***/viletech/"
keywords = ["bevy", "doom", "gamedev", "gzdoom", "viletech"]
license = "GPL-3.0-or-later"
publish = false
repository = "https://github.com/***REMOVED***/viletech/"

[dependencies]
viletech = { path = "../engine" }

bevy = { workspace = true }
bevy_egui = { workspace = true }
bitflags = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
indoc = { workspace = true }
kira = { workspace = true }
log = { workspace = true }
nanorand = { workspace = true }
parking_lot = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
