# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"engine",
	"client",
	"server"
]
default-members = ["engine", "client"]
# Needed for WGPU; having crates define edition 2021 does not suffice
resolver = "2"

# https://github.com/tesselode/kira/issues/24
[profile.dev.package.symphonia-bundle-mp3]
opt-level = 3
