[package]
name = "impure"
version = "0.0.0"
edition = "2021"
categories = ["games", "game-engines", "game-development"]
authors = ["***REMOVED***"]
description = "Experiments in a Doom source port"
homepage = "https://github.com/***REMOVED***/impure/"
license = "GPL-3.0-only"
repository = "https://github.com/***REMOVED***/impure/"
publish = false
keywords = ["game", "engine", "gamedev", "graphics", "doom"]
exclude = ["/svg", "/temp", "*.log"]

# WGPU requires cargo resolver v2
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
chrono = "0.4.19"
crossbeam = "0.8.1"
egui = "0.18"
egui-wgpu = "0.18"
egui-winit = "0.18"
fern = { version = "0.6.1", features = ["colored"] }
glam = { version = "0.21.2", features = ["approx", "bytemuck", "serde"] }
home = "0.5.3"
image = { version = "0.24.2", default-features = false, features = ["png"] }
lazy_static = "1.4.0"
log = "0.4.16"
luajit-src = "210.3.4"
md5 = "0.7.0"
mlua = { version = "0.7.4", features = [
	"luajit52",
	"vendored",
	"async",
	"send",
	"serialize",
] }
naga = "0.9.0"
nanorand = "0.7.0"
parking_lot = "0.12.1"
pollster = "0.2"
regex = "1.6.0"
serde = "1.0.140"
shipyard = { version = "0.5.0", features = ["serde1"] }
toml = "0.5.9"
wad = "0.3.2"
wgpu = "0.12"
winit = "0.26.1"
zip = "0.6.2"
zscript_parser = { version = "0.2.0", features = [
	"multithreaded",
	"gzd_folder_filesystem",
] }

[build-dependencies]
chrono = "0.4.19"
