[workspace]
members = [
	"engine",
	"client",
	"server"
]
default-members = ["engine", "client"]
# Needed for WGPU; having crates define edition 2021 does not suffice
resolver = "2"

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 4

# https://github.com/tesselode/kira/issues/24
[profile.dev.package.symphonia-bundle-mp3]
opt-level = 3

[workspace.dependencies]
bitflags = "1.3.2"
bitvec = { version = "1.0.1", features = ["serde"] }
bytemuck = { version = "1.11.0", features = ["derive"] }
chrono = "0.4.23"
clap = { version = "4.0.32", features = ["derive"] }
crossbeam = "0.8.2"
dashmap = { version = "5.4.0", features = ["rayon", "serde"] }
dolly = "0.4.0"
egui = "0.21.0"
fasthash = "0.4.0"
globset = "0.4.10"
indexmap = { version = "1.9.2", features = ["rayon", "serde"] }
indoc = "2.0.0"
itertools = "0.10.5"
kira = "0.7.1"
log = "0.4.17"
memoffset = "0.8.0"
nanorand = "0.7.0"
once_cell = "1.17.0"
parking_lot = { version = "0.12.1", features = ["arc_lock"] }
rayon = "1.6.1"
regex = "1.7.1"
renet = "0.0.9"
sha3 = "0.10.6"
walkdir = "2.3.2"
wgpu = "0.15.1"
winit = "0.28.1"
zip = "0.6.4"

# Temporary; will change to crates.io when one is suitable for publishing
doomfront = { path = "../doom-rs/doomfront", features = ["ser_de"] }
stardate = { path = "../doom-rs/stardate" }
subterra = { path = "../doom-rs/subterra" }
