[package]
name = "viletech"
description = "Feature- and modding-oriented Doom source port"
authors = ["***REMOVED***"]
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"
homepage = "https://github.com/***REMOVED***/viletech/"
repository = "https://github.com/***REMOVED***/viletech/"
categories = ["games", "game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "graphics", "doom"]
publish = false

[dependencies]
arrayvec = { workspace = true }
ariadne = { workspace = true }
bitflags = { workspace = true }
bitvec = { workspace = true }
bytemuck = { workspace = true }
byteorder = { workspace = true }
chrono = { workspace = true }
cpal = { workspace = true }
cranelift = { workspace = true }
cranelift-jit = { workspace = true }
cranelift-module = { workspace = true }
crossbeam = { workspace = true }
dashmap = { workspace = true }
dolly = { workspace = true }
doomfront = { workspace = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { workspace = true }
fasthash = { workspace = true }
fern = { workspace = true }
fixed = { workspace = true }
fluidlite = { workspace = true }
formatx = { workspace = true }
glam = { workspace = true }
globset = { workspace = true }
home = { workspace = true }
image = { workspace = true }
impl-trait-for-tuples = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
kira = { workspace = true }
log = { workspace = true }
md5 = { workspace = true }
memoffset = { workspace = true }
naga = { workspace = true }
nanorand = { workspace = true }
nodi = { workspace = true }
once_cell = { workspace = true }
palette = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
pollster = { workspace = true }
raw-cpuid = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
renet = { workspace = true }
rfd = { workspace = true }
serde = { workspace = true }
sha3 = { workspace = true }
stardate = { workspace = true }
subterra = { workspace = true }
toml = { workspace = true }
unicode-ident = { workspace = true }
walkdir = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
zip = { workspace = true }

[[bench]]
name = "bench"
harness = false

[build-dependencies]
chrono = { workspace = true }
miette = { version = "5.5.0", features = ["fancy"] }
sha3 = { workspace = true }
walkdir = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
criterion = "0.4.0"
