[package]
name = "viletech"
description = "Feature- and modding-oriented Doom source port"
authors = ["***REMOVED***"]
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/***REMOVED***/viletech/"
repository = "https://github.com/***REMOVED***/viletech/"
categories = ["games", "game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "graphics", "doom"]
publish = false

[dependencies]
bitflags = { workspace = true }
bytemuck = { workspace = true }
byteorder = "1.4.3"
chrono = { workspace = true }
cranelift = "0.91.0"
cranelift-jit = "0.91.0"
cranelift-module = "0.91.0"
crossbeam = { workspace = true }
dolly = { workspace = true }
doom-front = { workspace = true }
egui = { workspace = true }
egui-wgpu = "0.20.0"
egui-winit = "0.20.0"
fasthash = { workspace = true }
fern = { version = "0.6.1", features = ["colored"] }
fixed = "1.19.0"
formatx = "0.1.4"
glam = { version = "0.22.0", features = [
	"approx",
	"bytemuck",
	"rand",
	"serde",
	"debug-glam-assert",
] }
globset = { workspace = true }
home = "0.5.3"
image = { version = "0.24.4", default-features = false, features = [
	"dds",
	"jpeg",
	"png",
	"tga",
] }
indexmap = { workspace = true }
indoc = { workspace = true }
kira = { workspace = true}
log = { workspace = true }
md5 = "0.7.0"
mlua = { workspace = true }
naga = "0.10.0"
nanorand = { workspace = true }
num = "0.4.0"
num-traits = "0.2.15"
num-derive = "0.3.3"
once_cell = "1.15.0"
palette = "0.6.1"
parking_lot = { workspace = true }
peg = "0.8.1"
pollster = "0.2"
raw-cpuid = "10.6.0"
rayon = { workspace = true }
regex = { workspace = true }
renet = { workspace = true }
rfd = "0.10.0"
serde = "1.0.140"
sha3 = { workspace = true }
shipyard = { workspace = true }
str-utils = "0.1.6"
toml = "0.5.9"
unicode-width = "0.1.10"
unicode-xid = "0.2.4"
vec1 = { version = "1.10.1", features = ["serde"] }
walkdir = "2.3.2"
wgpu = { workspace = true }
winit = { workspace = true }
zip = { workspace = true }
zmusic = { workspace = true }

[[bench]]
name = "bench"
harness = false

[build-dependencies]
chrono = "0.4.19"

[dev-dependencies]
criterion = "0.3.6"
