[package]
name = "lithica"
version = "0.0.0"
edition.workspace = true

authors = ["jerome-trc"]
categories = ["compilers", "game-development"]
description = "Performant scripting language with powerful compile-time metaprogramming"
homepage = "https://github.com/jerome-trc/viletech/tree/master/lith"
keywords = ["compiler", "doom", "dsl", "gamedev", "scripting"]
license = "MIT OR Apache-2.0"
publish = false
repository.workspace = true

[dependencies]
doomfront = { path = "../doomfront" } # Only used for its parsing code.

ariadne.workspace = true
bitflags.workspace = true
bitvec.workspace = true
cranelift.workspace = true
cranelift-jit.workspace = true
cranelift-module.workspace = true
cranelift-interpreter.workspace = true
crossbeam.workspace = true
dashmap.workspace = true
logos.workspace = true
parking_lot.workspace = true
rustc-hash.workspace = true
smallvec.workspace = true

# All below are tentative. They will get marked as workspace dependencies if/as
# they prove to be sound and more performant than alternatives.
append-only-vec = "0.1.3"
backtrace = "0.3.69"
bumpalo = "3.14.0"
cee-scape = "0.1.6"
im = "15.1.0"
tiptoe = { version = "0.0.2", features = ["sync"] }
