[package]
name = "viletech-cli"
version = "0.0.0"
edition.workspace = true

categories = ["game-engines", "game-development"]
description = "VileTech Engine command line utilities"
keywords = ["bevy", "doom", "gamedev", "gzdoom", "viletech"]
license = "GPL-3.0-or-later"
publish = false
repository.workspace = true

[dependencies]
viletech = { path = "../engine" }

clap.workspace = true
indoc.workspace = true
