[package]
name = "impure-server"
description = "Headless dedicated server for Impure Engine"
authors = ["***REMOVED***"]
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/***REMOVED***/impure/"
repository = "https://github.com/***REMOVED***/impure/"
categories = ["games", "game-engines", "game-development"]
keywords = ["game", "engine", "gamedev", "graphics", "doom"]
publish = false

[dependencies]
impure = { path = "../engine" }

bitflags = { workspace = true }
bytemuck = { workspace = true }
clap = { version = "3.2.15", features = ["derive"] }
crossbeam = { workspace = true }
log = { workspace = true }
renet = { workspace = true }
sha3 = { workspace = true }
