id = 'viletech'
name = "$VILETECH_BASEDATA_NAME"
desc = "$VILETECH_BASEDATA_DESC"
authors = ["jerome-trc"]
copyright = "© 2022-2023 jerome-trc"
links = ['https://github.com/jerome-trc/viletech']
version = '0.0.0'

[[vzscript]]
name = 'vzscript'
root = 'vzscript/main.vzs'
version = '0.0.0'
